Astro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('universe_db/', include('universe_db.urls', namespace='universe_db')),  # point to your app's URLs
    path('', RedirectView.as_view(url='universe_db/', permanent=False)),  # Redirect base URL to homepage view

]

universe_db/urls.py
from django.urls import path
from . import views

app_name = 'universe_db'

urlpatterns = [
    path('', views.homepage, name='homepage'),

    path('planets/', views.planet_list, name='planet_list'),

    path('planets/<str:planet_name>/', views.planet_detail, name='planet_detail'),

    path('exoplanets/', views.exoplanets, name='exoplanets'),

    path('planetary-systems/', views.planetary_systems, name='planetary_systems'),

    path('calculate/', views.calculate, name='calculate'),

    #.as_view() is used because Django's URL routing expects a function and not a class
    path('planet-autocomplete/', views.PlanetAutocomplete.as_view(), name='planet-autocomplete', ),
    path('planetary-system-autocomplete/', views.PlanetarySystemAutocomplete.as_view(), name='planetary-system-autocomplete', ),

    path('mars_photos/', views.mars_photos, name='mars_photos'),

    path('nasa_photos/', views.nasa_photos, name='nasa_photos'),



]

universe_db/forms.py
from django import forms
from dal import autocomplete
from .models import SolarSystemPlanets, PlanetarySystems

class PlanetForm(forms.ModelForm):
    name = forms.ModelChoiceField(
        queryset=SolarSystemPlanets.objects.all(),
        widget=autocomplete.ModelSelect2(url='universe_db:planet-autocomplete')
    )

    class Meta:
        model = SolarSystemPlanets
        fields = ['name',]


class PlanetarySystemForm(forms.ModelForm):
    name = forms.ModelChoiceField(
        queryset=PlanetarySystems.objects.all(),
        widget=autocomplete.ModelSelect2(url='universe_db:planetary-system-autocomplete')
    )

    class Meta:
        model = PlanetarySystems
        fields = ['name',]

universe_db/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import RoverPhoto, NASAPhoto
import requests


# Create your views here.
# Generated by Django 4.2.2 on 2023-07-03 13:20
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from .models import SolarSystemPlanets, SSPMeasurement, PlanetarySystems
from django.core.paginator import Paginator
from django.db.models import Q
from math import pi, log
from dal import autocomplete
from .forms import PlanetForm, PlanetarySystemForm
import logging
import math


logger = logging.getLogger(__name__)

#------------------------------------------------------------------------------------------------------------------------------
# function to check if any values in an iterable are None
def any_none(values):
    return any(value is None for value in values)


#------------------------------------------------------------------------------------------------------------------------------
# views to handle various pages and actions on the website
def homepage(request):
    return render(request, 'universe_db/homepage.html')


#------------------------------------------------------------------------------------------------------------------------------
# fetches all planet objects and passes them to the 'planet_list' template
def planet_list(request):
    planets = SolarSystemPlanets.objects.all()
    return render(request, 'universe_db/planet_list.html', {'planets': planets})


#------------------------------------------------------------------------------------------------------------------------------
# fetches a single planet and its related measurements, and passes them to the 'planet_detail' template
def planet_detail(request, planet_name):
    planet = get_object_or_404(SolarSystemPlanets, name=planet_name)        #raises 404 error if the planet name object is not found
    measurements = SSPMeasurement.objects.filter(planet=planet)
    #print(planet)  # Check if planet data is correct
    #print(measurements)  # Check if measurements data is correct
    return render(request, 'universe_db/planet_detail.html', {'planet': planet, 'measurements': measurements})


#------------------------------------------------------------------------------------------------------------------------------
def exoplanets(request):
    planetary_systems = PlanetarySystems.objects.all()
    return render(request, 'universe_db/exoplanets.html', {'planetary_systems': planetary_systems})


#------------------------------------------------------------------------------------------------------------------------------
#fetches all planetary systems, filters them based on query parameters, paginates the results, and passes them to the 'planetary_systems' template
def planetary_systems(request):
    filtered_systems = PlanetarySystems.objects.all()

    # Get the search queries from the request parameters
    search_fields = [
        'name',
        'hostname',
        'number_of_stars',
        'number_of_planets',
        'discovery_method',
        'discovery_year',
        'discovery_facility',
        'orbit_period',
        'radius',
        'mass',
        'equilibrium_temperature',
        'spectral_type',
        'stellar_effective_temp',
        'stellar_mass',
        'stellar_metallicity',
        'stellar_metallicity_ratio',
        'stellar_surface_gravity',
        'ra',
        'dec',
        'distance',
        'eccentricity',
        'stellar_radius',
        'semimajor_axis',
        'impact_parameter',

    ]

    # Create a Q object to combine the query conditions
    q_object = Q()

    for field in search_fields:
        # Get the query parameter value
        query_value = request.GET.get(field, None)

        if query_value is not None and query_value != '':
            # Create a new Q object for this field and add it to the main Q object
            filtered_systems = filtered_systems.filter(**{f'{field}__contains': query_value})
            print(str(filtered_systems.query))



    filtered_systems = filtered_systems.order_by('id')
    paginator = Paginator(filtered_systems, 50)  # Number of items per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'request': request.GET,  # Pass the request.GET to access the search query in the template
        #'planetary_system_form': PlanetarySystemForm(),

    }

    return render(request, 'universe_db/planetary_systems.html', context)


#------------------------------------------------------------------------------------------------------------------------------
# handles various calculations for planets and planetary systems based on form data and calculation type
def calculate(request):
    # Create instances of both forms
    planet_form = PlanetForm(request.GET or None)
    planetary_system_form = PlanetarySystemForm(request.GET or None)

    logger.info('planet_form data: %s', planet_form.data)
    logger.info('planetary_system_form data: %s', planetary_system_form.data)

    # Initialize the result
    result = None

    # Get the selected calculation
    calculation = request.GET.get('calculation', None)
    logger.info('calculation: %s', calculation)

    # If a planet is selected
    if planet_form.is_valid():
        planet = planet_form.cleaned_data.get('name')
    else:
        planet = None
    logger.info('planet: %s', planet)

    # If a planetary system is selected
    if planetary_system_form.is_valid():
        planetary_system = planetary_system_form.cleaned_data.get('name')
    else:
        planetary_system = None
    logger.info('planetary_system: %s', planetary_system)



    #Constants:

    sigma = 5.67e-8     # Stefan-Boltzmann constant ( W/m^2.K^4 )
    grav_const = 6.67430 * (10**-11)    #Gravitational Constant (10⁻¹¹ m³ kg⁻¹ s⁻²)




    #EXOPLANET SURFACE GRAVITY
    if calculation == 'exo_surface_gravity':
        if any_none([planetary_system.mass, planetary_system.radius]):
            result = "Cannot calculate, insufficient data"
        else:
            exoplanet_mass = planetary_system.mass * 1.898e27
            exoplanet_radius = planetary_system.radius * 6.9911e7

            result = (grav_const * exoplanet_mass) / (exoplanet_radius**2)

    #STELLAR LUMINOSITY
    elif calculation == 'luminosity':
        if any_none([planetary_system.stellar_radius, planetary_system.stellar_effective_temp]):
            result = "Cannot calculate, insufficient data"
        else:
            star_radius = planetary_system.stellar_radius * 6.9634e8
            star_temperature = planetary_system.stellar_effective_temp

            # Estimate the luminosity of the star
            result = 4 * pi * (star_radius ** 2) * sigma * (star_temperature ** 4)

    #ESCAPE VELOCITY
    elif calculation == 'escape_velocity':
        if any_none([planetary_system.mass, planetary_system.radius]):
            result = "Cannot calculate, insufficient data"
        else:
            exoplanet_mass = planetary_system.mass * 1.898e27
            exoplanet_radius = planetary_system.radius * 6.9911e7

            result = (((2 * grav_const * exoplanet_mass) / exoplanet_radius)**.5) / 1000

    #EXOPLANET DENSITY
    elif calculation == 'exo_density':
        if any_none([planetary_system.mass, planetary_system.radius]):
            result = "Cannot calculate, insufficient data"
        else:
            exoplanet_mass = planetary_system.mass * 1.898e27
            exoplanet_radius = planetary_system.radius * 6.9911e7

            result = exoplanet_mass / ((4/3) * pi * exoplanet_radius**3)

    #TRANSIT DURATION
    elif calculation == 'transit_dur':
        exorad = planetary_system.radius * 0.10049
        semaxis = planetary_system.semimajor_axis * 215.032

        if any_none([planetary_system.orbit_period, planetary_system.stellar_radius, planetary_system.semimajor_axis, planetary_system.radius, planetary_system.impact_parameter, planetary_system.eccentricity]):
            result = "Cannot calculate, insufficient data"
        else:
            p1 = (planetary_system.orbit_period / pi)
            p2 = (planetary_system.stellar_radius / semaxis)
            p3 = ((1 + (exorad / planetary_system.stellar_radius))**2 - planetary_system.impact_parameter**2)**.5


            inner_asin = p2 * p3 / (1 - planetary_system.eccentricity**2)**.5
            print(inner_asin)

            if not -1 <= inner_asin <= 1:       #parameters of arcsin must be between -1 and 1 
                result = "Invalid input for arcsin function"
            else:
                result = p1 * math.asin(inner_asin)











    logger.info('result: %s', result)

    if result is not None:  # Makes sure that result is not None before comparing
        if isinstance(result, float) and result > 10000:  # Check if the result is a float
            result = "{:.3e}".format(result)
        elif isinstance(result, float):  # Check if the result is a float
            result = "{:.3f}".format(result)


    return render(request, 'universe_db/calculations.html', {'result': result, 'planet_form': planet_form, 'planetary_system_form': planetary_system_form, 'calculation': calculation})

#------------------------------------------------------------------------------------------------------------------------------
# Defines a custom autocomplete view for planet and planetary system selection in forms
class PlanetAutocomplete(autocomplete.Select2QuerySetView):

    #define what data should be returned based on the search term.
    def get_queryset(self):

        # If the user making the request is not authenticated, no planets are returned.
        if not self.request.user.is_authenticated:
            return SolarSystemPlanets.objects.none()

        # Start with a queryset that includes all planets.
        qs = SolarSystemPlanets.objects.all()

universe_db/templates/universe_db/calculations.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head><script src="{% static 'js/color-modes.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Calculations</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=REM:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=REM:wght@500&family=Roboto&display=swap" rel="stylesheet">

    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>
    <script src="{% static 'autocomplete_light/select2.js' %}"></script>
    <script src="{% static 'autocomplete_light/jquery.post-setup.js' %}"></script>


    <style>

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            border-right: 1px solid #ddd;
        }

        th:last-child, td:last-child {
            border-right: none;
        }

        .pagination {
            margin-top: 10px;
        }

        .pagination a {
            display: inline-block;
            padding: 5px 10px;
            background-color: #f2f2f2;
            color: #333;
            text-decoration: none;
            border: 1px solid #ddd;
        }

        .pagination .current-page {
            font-weight: bold;
        }

        .search-form {
            margin-bottom: 20px;
        }

        .search-box {
            margin-right: 10px;
        }

        .search-button {
            margin-left: 10px;
        }

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }

        #header-background
        {
            background: url('/static/images/deepfield3.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        #footer-background
        {
            background: url('/static/images/deepfield3.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        .planet-name
        {
          text-decoration: none;
        }

        .my-carousel
        {
          margin-bottom: 50px;  /* Adjust the value to get the desired gap */
        }

        .navbar
        {
            width: 110% !important;
        }

        .navbar-brand
        {
          box-shadow: none !important;
        }

        body, .container-fluid
        {
          max-width: 100%;
          overflow-x: hidden; /* To hide horizontal scroll */
        }

    </style>


</head>
<body>

   <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>


    <header data-bs-theme="dark">
      <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4>About me</h4>
              <p class="text-body-secondary">I'm a recent graduate from Rutgers University, with a Physics BS (Astrophysics) and a minor in Computer Science. My academic journey, fueled by a deep fascination for astronomy and a keen interest in software development, has given me a strong footing in both worlds. Recently, I delved into web development, leveraging Python, Django, and Bootstrap to create robust and responsive websites. After successfully developing a full-stack website, I'm now poised to embark on a journey as a full-stack developer, combining my passion for problem-solving with my software skills. Simply put, I love learning, love challenges, and am excited to make my mark in the field of computer science and web development.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4>Contact me</h4>
              <ul class="list-unstyled">
                <li><a href="https://www.linkedin.com/in/pierce-makombe-5a8406221" class="text-white">LinkedIn</a></li>
                <li><a href="{% static 'files/Resume.pdf' %}" target="_blank" class="text-white">Resume</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container-fluid">
          <a class="navbar-brand bg-dark fw-light color_white" href="{% url 'universe_db:homepage' %}">
              <div>
                <img src="{% static 'images/Icon.PNG' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                Astro
              </div>
              <div>
                  Calculations
              </div>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>


     <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col" style="padding-right: 0px;padding-left: 0px;">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
          <div class="card-header py-3 text-bg-primary border-primary">
            <h4 class="my-0 fw-normal">Calculations</h4>
          </div>
          <div class="card-body">
            <!-- Form to input the planet or planetary system name and choose the calculation type -->
            <form method="GET" action="{% url 'universe_db:calculate' %}">
                <h3>
                    <!-- Planetary system form field -->
                    <label for="calculation">Planet</label>
                    {{ planetary_system_form.name.label_tag }} {{ planetary_system_form.name }}

                </h3>
                    <div style="display: flex; align-items: center; justify-content: center; margin-top: 30px;">
                        <h3 for="calculation" style="margin-right: 10px;">
                            Calculation Type:
                        </h3>
                        <select id="calculation" name="calculation" style="margin-right: 10px;" class="btn btn-secondary dropdown-toggle">
                            <option value="exo_surface_gravity">Surface Gravity</option>
                            <option value="luminosity">Stellar Luminosity</option>
                            <option value="escape_velocity">Escape Velocity</option>
                            <option value="exo_density">Exoplanet Density</option>
                            <option value="transit_dur">Transit Duration</option>
                        </select>
                    </div>
                <input type="submit" value="Calculate" class="btn btn-lg btn-success" style="margin-top: 20px; width:20%; font-family: 'Roboto', sans-serif !important;">
            </form>
            <div style="margin-top: 20px;">
                {% if result and result != 'Cannot calculate, insufficient data' %}
                    <h3>Calculation Result:</h3>
                    {% if calculation == "exo_surface_gravity" %}
                        <div style="font-family: 'Roboto', sans-serif !important; font-size: 20px; color:green">The Surface Gravity of the selected exoplanet is: {{ result }} m/s²</div>
                    {% elif calculation == "luminosity" %}
                        <div style="font-family: 'Roboto', sans-serif !important; font-size: 20px; color:green">The Stellar Luminosity of the host star is: {{ result }} W</div>
                    {% elif calculation == "escape_velocity" %}
                        <div style="font-family: 'Roboto', sans-serif !important; font-size: 20px; color:green">The Escape Velocity of the selected exoplanet is {{ result }} km/s</div>
                    {% elif calculation == "exo_density" %}
                        <div style="font-family: 'Roboto', sans-serif !important; font-size: 20px; color:green">The Density of the selected exoplanet is {{ result }} kg/m³</div>
                    {% elif calculation == "transit_dur" %}
                        <div style="font-family: 'Roboto', sans-serif !important; font-size: 20px; color:green">The Transit Duration of the exoplanet is {{ result }} days</div>
                    {% endif %}
                {% else %}
                    <h3>Calculation Result: <span style="color: red;">Cannot calculate, insufficient data</span></h3>

                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>







    {{ planet_form.media }}
    {{ planetary_system_form.media }}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>



</body>
</html>

universe_db/templates/universe_db/exoplanets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Exoplanets</title>
</head>
<body>
    <h1>Exoplanets</h1>

    <a href="{% url 'universe_db:planetary_systems' %}">Planetary Systems</a>
</body>
</html>

universe_db/templates/universe_db/homepage.html
<!DOCTYPE html>
<html lang="en" style="height: 100%;">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">    <!-- Responsive design meta tag -->
    <title>Astronomical Objects Database</title>


    <link href="{% static 'css/styles.css' %}" rel="stylesheet">    <!-- Link to custom CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">   <!-- Link to Bootstrap CSS for styling the page using Bootstrap -->


</head>
<body class="homepage-body d-flex h-100 text-center text-white bg-dark" style="height: 100%;">  <!-- Bootstrap classes for the styling of the body -->

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">    <!-- Bootstrap classes for styling the content wrapper -->

        <header class="mb-auto">     <!-- A Bootstrap class for setting the margin-bottom to auto -->
            <div class="d-flex align-items-center">
                <img src="{% static 'images/Icon.PNG' %}" width="35" height="35" class="d-inline-block align-top" alt="">
                <h3 class="mb-0" style="font-size: 40px; margin-left: 10px;">Astrolarity</h3>
            </div>
        </header>

        <main class="px-3">    <!-- for grid layout and alignment -->

            <h1>Welcome to the Astronomical Objects Database</h1>
            <p class="lead">Explore our collection of Solar System Planets, Exoplanets, and more!</p>

            <div class="row justify-content-center">
                <div class="col-lg-4">  <!-- for setting the width of the element on large screens -->

                <!-- for styling the button -->
                    <h3><a class="btn btn-lg fw-bold border-white bg-white" href="{% url 'universe_db:planet_list' %}"style="--bs-btn-hover-color: black">Solar System Planets</a></h3>
                </div>
                <div class="col-lg-4">
                    <h3><a class="btn btn-lg fw-bold border-white bg-white" href="{% url 'universe_db:planetary_systems' %}" style="--bs-btn-hover-color: black">Exoplanets</a></h3>
                </div>
                <div class="col-lg-4">
                    <h3><a class="btn btn-lg fw-bold border-white bg-white" href="{% url 'universe_db:calculate' %}" style="--bs-btn-hover-color: black">Calculations</a></h3>
                </div>
            </div>
        </main>

        <footer class="mt-auto text-white-50">  <!-- for setting the margin-top to auto and the text color to 50% white -->
            <p>All images and data courtesy of NASA, ESA, CSA, and STScI</p>
        </footer>
    </div>


    <!-- Link to Bootstrap JS for enabling the functionalities of Bootstrap components -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>